# Generated by Django 4.1.3 on 2022-12-04 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owlBumsApp', '0002_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='albumArist',
            field=models.CharField(default='Album Artist', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='albumGenre',
            field=models.CharField(default='Genere', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='albumName',
            field=models.CharField(default='Album Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default='Anon', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='Album Review', max_length=255),
        ),
    ]
