# Generated by Django 4.1.3 on 2022-12-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0003_review_albumarist_review_albumgenre_review_albumname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='albumArist',
            new_name='albumArtist',
        ),
    ]
