# Generated by Django 4.1.3 on 2022-12-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0005_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='albumGenre',
            field=models.CharField(default='Genre', max_length=255),
        ),
    ]
