# Generated by Django 4.1.3 on 2022-12-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0006_alter_review_albumgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
