# Generated by Django 4.1.3 on 2022-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0008_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='albumArtist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='albumGenre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='albumName',
            field=models.CharField(max_length=255),
        ),
    ]
