# Generated by Django 4.1.3 on 2022-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0009_alter_review_albumartist_alter_review_albumgenre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
