# Generated by Django 4.1.3 on 2022-12-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
