# Generated by Django 4.1.3 on 2022-12-05 21:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0013_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
