# Generated by Django 4.1.3 on 2022-12-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlBumsApp', '0014_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='albumArt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
